name: Container Claus

on:
  push:
    branches:
      - 'master'
    tags:
      - '*'

jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      MAKEFLAGS: -j3
      SOURCE_COMMIT: ${GITHUB_SHA}
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Find build version
        id: vars
        run: |
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          if [ "$VERSION" = "master" ]; then
            echo "tags=troglobit/inadyn:build-${GITHUB_RUN_NUMBER}" >> $GITHUB_OUTPUT
          else
            echo "tags=troglobit/inadyn:$VERSION,troglobit/inadyn:latest" >> $GITHUB_OUTPUT
          fi
      - uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ steps.vars.outputs.tags }}
          platforms: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64,linux/ppc64le
  ghcr:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    env:
      MAKEFLAGS: -j3
      IMAGE_NAME: inadyn
      SOURCE_COMMIT: ${GITHUB_SHA}
    steps:
      - uses: actions/checkout@v3
      - name: Build image
        run: docker buildx build . --file Dockerfile --tag $IMAGE_NAME --label "runnumber=${GITHUB_RUN_ID}"
      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Push image
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME
          # Change all uppercase to lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          if [ "$VERSION" = "master" ]; then
            VERSION="build-${GITHUB_RUN_NUMBER}"
          else
            VERSION="$VERSION latest"
          fi
          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION
          for ver in $VERSION; do
            docker tag $IMAGE_NAME $IMAGE_ID:$ver
            docker push $IMAGE_ID:$ver
          done
